import { Router } from "express";
import { authenticate } from "../middleware/authMiddleware.js";
import { getAllReferral, getReferralCode, getReferralCommissions, getReferralTree, giveReferral } from "../controllers/referralController.js";
const router = Router();
router.get("/", authenticate, getAllReferral);
router.get("/code", authenticate,getReferralCode);
router.post("/refer", authenticate,giveReferral);
router.get("/tree", authenticate,getReferralTree);
router.get("/commissions", authenticate,getReferralCommissions);
export default router;